### ISSUE TITLE
Can't set previewer's border

### ISSUE THREAD

**Issue by yukimemi** [uga-rosa/ddc-previewer-floating#5]
The border setting for preview is specified on-code.
I want it to be user configurable.

https://github.com/uga-rosa/ddc-previewer-floating/blob/daa833f67446373339e5965d6a2ec3c1a9b32a52/lua/ddc_previewer_floating/view.lua#L56

**Comment by uga-rosa** [comment]
Done in 8316c319a3f56f984172a8e37533c6beee6f5416.
